package com.chatop.demo.controller;

import com.chatop.demo.dto.RegisterDTO;
import com.chatop.demo.model.User;
import com.chatop.demo.repository.UserRepository;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(path="/auth")

public class AuthController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/register") // Map ONLY POST Requests
    public String addNewUser (@RequestBody RegisterDTO registerDTO) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(registerDTO.getName());
        n.setEmail(registerDTO.getEmail());
        n.setPassword(registerDTO.getPassword());
        userRepository.save(n);
        return "Saved";
    }
}